### PR TITLE
Create BakerAaron

### PR DESCRIPTION
**Pull request by nbakeraaron**

### CODE REVIEW

**Comment by heike** [comment]
@nbakeraaron add the extension rmd to your file and put in another pull request.

**Comment by nbakeraaron** [comment]
Closed? Does that mean that I don't need to do that anymore?

Sorry I am using an email that isn't my school one so it's not one I check
everyday.

**Comment by heike** [comment]
@nbakeraaron no, that's not what that means - it just means: add the extension rmd to your file and submit a new pull request.

**Comment by nbakeraaron** [comment]
Ah,and here lies the problem with me not checking this email very often -_-

**Pull request closed without merging**
